f1 = input("Enter text to write to the file: ")
f = open('output.txt', 'w')
f.write(f1 + '\n')
f.close()
print("Data successfully written to output.txt.")
add = input("Enter additional text to append: ")
f = open('output.txt', 'a')
f.write(add + '\n')
f.close()
print("Data successfully appended.")
print("\nFinal content of output.txt:")
f = open('output.txt', 'r')
print(f.read())
f.close()
